### ISSUE TITLE
Cant add other door

### ISSUE THREAD

**Issue by thisisyoursus** [JustMarfix/DoorsExplosionResistance#1]
i try add HID_LEFT and HID_RIGHT BUT ITS NOT WORKED!!!!!!!!!!!!!!!

**Comment by JustMarfix** [comment]
Will be fixed in 1-2 days.

**Comment by thisisyoursus** [comment]
wait i think i forget just just HID_RIGHT
i forget remove _ sorry bro

**Comment by JustMarfix** [comment]
@thisisyoursus fixed.
